import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Tabs from "./components/ui/Tabs";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Dashboard visualización",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" data-theme="light" className="py-[30px] px-[50px] bg-base-300">
      <body>
        <header>
          <Tabs />
        </header>
        <main className="p-6 border-[1px] border-t-[0px] rounded-b-[10px] bg-base-100 border-base-300">
          {children}
          <div></div>
        </main>
        <footer>© 2025 My Website</footer>
      </body>
    </html>
  );
}
